# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-02 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emplayapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='stage',
            field=models.CharField(max_length=4),
        ),
    ]
